### ISSUE TITLE
another error with GenerateEdgeWeights

### ISSUE THREAD

**Issue by wfma** [VCCRI/scTalk#4]
Hi Ralph and colleagues,

I am encountering a new error with GenerateEdgeWeights() while applying it to a new dataset published on COVID PMBCs by the Blish group.

Here is what I see,

```
> populations.use <- names(blish@meta.data[["SingleR.calls"]]) #i used singleR's annotation here
> ## Define a label for output files
> file.lab <- "TIP"

> GenerateEdgeWeights(seurat.object = blish,
+                     file.label = file.lab, # output file
+                     species = "human",
+                     populations.use = populations.use,
+                     string.ver = "11.0",
+                     verbose = TRUE) # this is a bug, need to run this line
[1] "Calculating cluster-specific ligand/expression characteristics"
Error in apply(expression.matrix[, cell.set], 1, function(x) { : 
  dim(X) must have a positive length
```

I rechecked and this operation worked on my previous dataset. I am not sure what the error means,

Wei

**Comment by rj-patrick** [comment]
Hi Wei,

If the populations you are selecting are not active identities in your Seurat object, then they won't be detected by scTalk. Try setting them first, i.e.:

```
populations.use <- names(blish@meta.data[["SingleR.calls"]]) #i used singleR's annotation here
Idents(blish) <- blish@meta.data[["SingleR.calls"]]
```

Then run GenerateEdgeWeights again.

Cheers,
Ralph

**Comment by wfma** [comment]
Thanks! I feel like I had this issue earlier but couldnt find the solution. Thanks again.
Wei
