### ISSUE TITLE
CellCirclePlot title

### ISSUE THREAD

**Issue by PaulaNietoG** [VCCRI/scTalk#5]
Hello all!

I'm using scTalk a lot lately and I was wondering what is the correct way to add a title to a `CellCirclePlot`. I have tried with the base `main` parameter as well as ggplot's `labs(title = "my title")` but none of them seem to work.

Could you help with this?

Thanks a lot!

Paula

**Comment by rj-patrick** [comment]
Hi Paula,

`CellCirclePlot` actually uses R's standard `plot` function, so to add a title you would need to run `title(main = 'my title')`. However, I've also modified `CellCirclePlot` to allow the setting of a title using a `title` parameter - this option is probably easier as the figure margins are optimized.

Cheers,
Ralph

**Comment by PaulaNietoG** [comment]
Great. Thanks a lot, Ralph!

Paula
