### ISSUE TITLE
Error with EvaluateConnections 

### ISSUE THREAD

**Issue by Jeff87075** [VCCRI/scTalk#6]
Hi, thanks for the nice package, I just want to ask what is the difference between the ```populations.use``` argument and ```pct.threshold``` argument in the ```GenerateEdgeWeights()``` function? 

Also, since I have to run the workflow a lot of times across different combinations I've been trying to run the ```EvaluateConnections()``` with different ```populations.use``` however I'm getting these errors how can I solve them? 
```
Error in { : 
  task 2 failed - "cannot take a sample larger than the population when 'replace = FALSE'"
In addition: Warning message:
In e$fun(obj, substitute(ex), parent.frame(), e$data) :
  already exporting variable(s): complete.path.table, background.table
```

**Comment by rj-patrick** [comment]
Hi @Jeff87075,

A fix has been submitted that should allow you to run the package without error.

Cheers,
Ralph
